Update test-unit bundle to run race detector
It will run twice each package test, one without the race detector, one
with.

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

diff --git a/script/test-unit b/script/test-unit
--- a/script/test-unit
+++ b/script/test-unit
@@ -28,16 +28,28 @@ fi
 
 TESTS_FAILED=()
 
+set +e
 for dir in $TESTDIRS; do
     echo '+ go test' $TESTFLAGS "${LIBCOMPOSE_PKG}/${dir#./}"
     go test ${TESTFLAGS} "${LIBCOMPOSE_PKG}/${dir#./}"
     if [ $? != 0 ]; then
         TESTS_FAILED+=("$dir")
         echo
-        echo "${RED}Tests failed: $dir${TEXTRESET}"
+        echo "${RED}Tests failed: ${LIBCOMPOSE_PKG}${TEXTRESET}"
         sleep 1 # give it a second, so observers watching can take note
+    else
+        echo '+ go test -race' $TESTFLAGS "${LIBCOMPOSE_PKG}/${dir#./}"
+        go test -race ${TESTFLAGS} "${LIBCOMPOSE_PKG}/${dir#./}"
+        if [ $? != 0 ]; then
+            TESTS_FAILED+=("$dir")
+            echo
+            echo "${RED}Tests failed (race): ${LIBCOMPOSE_PKG}${TEXTRESET}"
+            sleep 1 # give it a second, so observers watching can take note
+        fi
     fi
 done
+set -e
+
 echo
 
 # if some tests fail, we want the bundlescript to fail, but we want to
